### ISSUE TITLE
Please consider a project rename.

### ISSUE THREAD

**Issue by ausmith** [cbdr/newrelic-rpm#1]
Yes, this project is forked from https://github.com/newrelic/rpm, but that is not obvious until you dig into the project. Possibly newrelic-rpm? Having a project called rpm in cbdr makes me think we have a fork of an upstream package manager, which is just confusing (and limiting if/when we decide to actually create an RPM down the road for some reason or another)!

**Comment by bmillsofthesky** [comment]
I've renamed the repository as requested. Sorry for the confusion here. First time forking from third party.

**Comment by ausmith** [comment]
:+1: thanks for the quick change!
